Script started on 2022-01-20 13:43:39-05:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="109" LINES="23"]
]0;jav86@gold18: ~/CS214/labs/02[01;32mjav86@gold18[00m:[01;34m~/CS214/labs/02[00m$ cat example6.lex example6.y
%{
#include <stdio.h>
#include <stdlib.h>           /* atoi() */
#include <string.h>           /* strcmp() */
#include "example6.tab.h"
%}
%%
[0-9]+                  yylval = atoi(yytext); return NUMBER;
heat                    return TOKHEAT;
on|off                  yylval = !strcmp(yytext,"on"); return STATE;
set                     return TOKSET;
temperature             return TOKTEMPERATURE;
humidity                return TOKHUMIDITY;
\n                      /* ignore end of line */;
[ \t]+                  /* ignore whitespace */;
%%%{
#include <stdio.h>
#include <string.h>

/* declarations */
int yylex (void);
void yyerror (char const *);
int yyparse(void);

/* definitions */ 
void yyerror(const char *str) {
        fprintf(stderr,"error: %s\n",str);
}
 
int yywrap() {
        return 1;
} 
 
int main() {
        yyparse();
} 

%}

%token NUMBER TOKHEAT STATE TOKSET TOKTEMPERATURE TOKHUMIDITY
%%

commands: /* empty */
        | commands command
        ;

command:
        heat_switch
        | temperature_set
        | humidity_set
        ;

heat_switch:
        TOKHEAT STATE
        {
                if ($2) {  /* if STATE == 1 */
                        printf("\tHeat turned on\n");
                } else {
                        printf("\tHeat turned off\n");
                }
        }
        ;

temperature_set: 
        TOKSET TOKTEMPERATURE NUMBER
        {
                printf("\tTemperature set to %d\n",$3);
        }
        ;

humidity_set: 
        TOKSET TOKHUMIDITY NUMBER
        {
                printf("\tHumidity set to %d\n",$3);
        }
        ;]0;jav86@gold18: ~/CS214/labs/02[01;32mjav86@gold18[00m:[01;34m~/CS214/labs/02[00m$ make
make: 'example6' is up to date.
]0;jav86@gold18: ~/CS214/labs/02[01;32mjav86@gold18[00m:[01;34m~/CS214/labs/02[00m$ make
make: 'example6' is up to date.
]0;jav86@gold18: ~/CS214/labs/02[01;32mjav86@gold18[00m:[01;34m~/CS214/labs/02[00m$ e \ ./example6
heat on
	Heat turned on
heat off
	Heat turned off
tem   set temperature 400
	Temperature set to 400
set temperature 30
	Temperature set to 30
set humidity 400
	Humidity set to 400
set humidity 30
	Humidity set to 30
done    exit    ]0;jav86@gold18: ~/CS214/labs/02[01;32mjav86@gold18[00m:[01;34m~/CS214/labs/02[00m$ done    exit
exit

Script done on 2022-01-20 13:45:12-05:00 [COMMAND_EXIT_CODE="0"]
